// vue-client/src/views/About.vue
<template>
    <div id="about">
        <div class="jumbotron bg-primary text-white">
            <h1 class="display-3">Vue Movie Finder!💚</h1>
            <p class="lead">This is a simple app for searching movies with 
                <a href="http://www.omdbapi.com/" target="_blank" class="text-warning"> omdb API </a> 
                and
                <a href="https://vuejs.org" target="_blank" class="text-success"> Vue.js </a> 
            </p>
            <p class="lead">
                <a class="btn btn-secondary " href="https://github.com/flx86/cinex" role="button" target="_blank">GitHub</a>
                <router-link class="btn btn-link" :to="'/'">Go Back To Search</router-link>
            </p>
        </div>
    </div>
</template>

<script>
export default {
    
}
</script>

<style scoped>

    .jumbotron{
        width: 70%;
        margin: 80px auto;
        border-radius: 8px;
        padding: 20px;


    }

</style>

// react-client/src/views/About.js
import React, {Component} from 'react'
import { Link } from 'react-router-dom'

class About extends Component {
  
  render (){
    return (
      
    <div style={aboutContainer} className="jumbotron bg-primary text-white">
        <h1 className="display-3">React Movie Finder! <span role="img" aria-label="emojis">💙✨</span> </h1>
        <p className="lead">This is a simple app for searching movies with
            <a 
              href={'http://www.omdbapi.com/'} target="_blank" className="text-warning"
              rel="noopener noreferrer"
            > omdb API </a>  and
            <a
              href={'https://reactjs.org/'} target="_blank" className="text-info"
              rel="noopener noreferrer"
            > React.js </a> 
        </p>
        <p className="lead">
            <a 
              className="btn btn-secondary " href={'https://github.com/flx86/cinex'} target="_blank"
              rel="noopener noreferrer"
            >GitHub</a>
            <Link className="btn btn-link" exact to="/">Go Back To Home</Link>
        </p>
    </div> 
    )
  }  
}

// Styles
const aboutContainer = {
  width: '80%',
  margin: '80px auto'
}

export default About
