// vue-client/src/views/Home.vue
<template>
  <div class="home">
    <SearchMovie/>
    <VueLoading v-show="loading"/>
    <main class="movies card-columns" v-show="!loading && moviesFound">
      
      <MovieCard 
        v-for="movie in movies" 
        :key="movie.id"
        :movie="movie" 
      />

    </main>    
    <div class="alert alert-danger"  v-show="!loading && !moviesFound">
      <strong>Oh snap! Movie Not Found!😞 </strong>
    </div>
    
  </div>
</template>

<script>
// @ is an alias to /src

  import SearchMovie from "@/components/SearchMovie.vue";
  import MovieCard from "@/components/MovieCard.vue";
  import VueLoading from "@/components/VueLoading.vue";
  import { mapState } from "vuex";

  export default {
    name: 'home',
    components: {
      SearchMovie,MovieCard,VueLoading
    },
    computed: mapState({
      loading : 'loading',
      movies : 'movies',
      moviesFound: 'moviesFound',
    }),
  }
</script>

<style scoped>

  .movies{
    width: 80%;
    margin: 0 auto;
    text-align: center;
    column-gap: 0.025rem;
  }

  .alert{
    width: 25%;
    margin: 0 auto;
    text-align: center;
  }

  

</style>

// react-client/src/views/Home.js
import React, {Component} from 'react';
import SearchMovie  from '../components/SearchMovie';
import ReactLoading  from '../components/ReactLoading';
import MovieCard from '../components/MovieCard'


import API  from  '../API';

class Home extends Component {

  state ={
    movies:[],
    loading:false,
    movieSearched:'',
    response: Boolean,
  }

  searchMovie = async (movie) => {
    this.setState({loading:true});

    const url = `${API.URL_TITLE}${movie}`;
    const res = await fetch (url);
    const data = await res.json();

    this.setState({loading:false});

    if (!data.response){
      this.setState({movies:[]});
    }

    this.setState({...data}); 
  }

  render(){
    const {loading, response} = this.state;

    return (
      <React.Fragment>
        <SearchMovie searchMovie={this.searchMovie}/>

        {
          loading ? <ReactLoading/> : 
            <main style={movieContainer} className="card-columns">
              {
                this.state.movies.map((movie,key) => {
                  return ( <MovieCard key={key} movie={movie} />)
                })
              }
          </main>
        }

        {
          !response ?
            <section style={alertContainer} className="alert alert-danger">
              <strong>Oh snap! Movie Not Found! <span role="img" aria-label="sad">😞</span></strong>
            </section>
          :
            ''
        }

      </React.Fragment>
    )
  }
}
const movieContainer={width:'80%',margin:'0 auto', }
const alertContainer = {width: '20%',margin: '0 auto'}
export default Home
