// react-client/src/components/NavBar.js
import React , { Component } from 'react';
import { NavLink } from 'react-router-dom';

class NavBar extends Component {

  render (){
    return (
      <div>
        <nav className="navbar navbar-expand-lg navbar-dark bg-primary">
        <NavLink className= "navbar-brand" exact to= "/">Cinex</NavLink> 
          <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span className="navbar-toggler-icon"></span>
          </button>

          <div className="collapse navbar-collapse" id="navbarColor01">
            <ul className="navbar-nav mr-auto">
              <li className= "nav-item">
                <NavLink 
                  className="nav-link" 
                  exact to="/" 
                  activeStyle={{color:'#02d9ff'}}

                >Home</NavLink> 
              </li>
              <li className="nav-item" >
                <NavLink 
                  className="nav-link" 
                  exact  to="/about"
                  activeStyle={{color:'#02d9ff'}}  
                >About</NavLink> 
              </li>
            </ul>
          </div>
        </nav>
      </div>
    )
  }
  

}


       
export default NavBar

// vue-client/src/components/Navbar.vue
<template>
    <div id="navbar">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <router-link class="navbar-brand" :to="'/'">CINEX</router-link>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor03">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item" :class="{active: isHome}">
                         <router-link class="nav-link" :to="'/'">Home</router-link>
                    </li>
                    <li class="nav-item" :class="{active: isAbout}">
                         <router-link class="nav-link" :to="'/about'">About</router-link>
                    </li>
                </ul>
            </div>
        </nav>
    </div>


</template>

<script>
    export default {
        computed:{
            isAbout(){
                return this.$route.path === '/about';
            },
            isHome(){
                return this.$route.path === '/';
            }
        }
    }
</script>

<style scoped>

</style>
