// react-client/src/components/SearchMovie.js
import React, { Component } from 'react'

export class SearchMovie extends Component {

  state ={
    movie:''
  }

  onChange = (e) => { 
    this.setState({
      [e.target.name]: e.target.value
    })

  }

  onSubmit = (e) => {
    e.preventDefault();
    this.props.searchMovie(this.state.movie);
    this.setState({movie:''});
  }
  render() {
    return (
      <div className="search-movie-container bg-light">
        <h3>Search a Movie</h3>
        <form className="form-group" onSubmit={this.onSubmit}>
          <input  
            className="form-control" type="text" name="movie" placeholder="Enter a movie title..."
            autoComplete="off"
            onChange={this.onChange} value={this.state.movie}
          />
          <button className="btn btn-info mt-2" type="submit" >Search</button>
        </form>
      </div>
    )
  }
}

export default SearchMovie

// vue-client/src/components/SearchMovie.vue
<template>
    <form id="search-movie" class="bg-light" @submit.prevent="onSearchMovie">
        <div class="form-group">
            <h3>Search a movie</h3>
            <input 
                type="text" 
                class="form-control" 
                id="movie" 
                placeholder="Enter a movie title"
                autocomplete="off"
                v-model="movieTitle"
            >
            <button 
                 type="submit" 
                 class="btn btn-danger mt-2"
            >Search</button>
        </div>
    </form>

</template>

<script>

    export default {
        name:"search-movie",
        components:{

        },
        data(){
            return {
                movieTitle:''
            }
        },
        methods:{
            onSearchMovie(event){
                event.target.reset();
                this.searchMovie();
            },
            searchMovie(){
                this.$store.dispatch('searchMovie',{
                    movieTitle: this.movieTitle,
                });
            }
        }
}
</script>

<style>
    #search-movie{
        width: 55%;
        margin: 30px auto;
        border-radius: 8px;
        padding: 20px;
    }


</style>
